# Generated by Django 3.1.3 on 2021-08-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingstrategy',
            name='key_2',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='userexperiencestrategy',
            name='key_2',
            field=models.CharField(default='', max_length=50),
        ),
    ]
