# Generated by Django 3.1.3 on 2021-08-09 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20210809_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketingstrategy',
            name='key_2',
        ),
        migrations.RemoveField(
            model_name='userexperiencestrategy',
            name='key_2',
        ),
    ]
