# Generated by Django 3.1.3 on 2021-08-10 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_marketstrategy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MarketingStrategy',
        ),
    ]
