# Generated by Django 3.1.3 on 2021-08-10 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_auto_20210810_1912'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MarketingStrategy',
        ),
    ]
