# Generated by Django 3.1.3 on 2021-08-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_marketingstrategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingstrategy',
            name='khaled',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
