# Generated by Django 3.1.3 on 2021-08-10 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_marketingstrategy_khaled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketingstrategy',
            name='khaled',
        ),
    ]
