# Generated by Django 3.1.3 on 2021-07-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rest_id', models.CharField(max_length=20)),
                ('menu_name', models.CharField(max_length=20)),
                ('dish_id', models.CharField(max_length=20)),
                ('menu_id', models.CharField(max_length=20)),
                ('dish_name', models.CharField(max_length=50)),
                ('dish_price', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('rest_name', models.CharField(max_length=50)),
                ('rest_a_name', models.CharField(max_length=50)),
            ],
        ),
    ]
