# Generated by Django 3.1.3 on 2021-07-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_menu', '0003_dish_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dish',
            name='dish_id',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='dish',
            name='dish_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='dish',
            name='dish_price',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='dish',
            name='menu_id',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='dish',
            name='menu_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='dish',
            name='rest_a_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dish',
            name='rest_id',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='dish',
            name='rest_name',
            field=models.CharField(max_length=50),
        ),
    ]
