# Generated by Django 3.1.3 on 2021-07-30 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_menu', '0004_auto_20210727_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_address', models.CharField(max_length=50)),
                ('restaurant_name', models.CharField(max_length=50)),
                ('restaurant_a_name', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=40)),
                ('restaurant_id', models.CharField(max_length=30)),
                ('rate', models.CharField(max_length=10)),
                ('order_time', models.CharField(max_length=30)),
                ('bill_total', models.CharField(max_length=20)),
                ('paid', models.CharField(max_length=5)),
                ('order_id', models.CharField(max_length=50)),
                ('dish_id', models.CharField(max_length=50)),
                ('bill_id', models.CharField(max_length=50)),
                ('dish_price', models.CharField(max_length=20)),
                ('quantity', models.CharField(max_length=10)),
                ('order_total', models.CharField(max_length=10)),
                ('user_address_label', models.CharField(max_length=50)),
                ('user_address', models.CharField(max_length=50)),
            ],
        ),
    ]
