# Generated by Django 3.1.3 on 2021-07-31 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_menu', '0005_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('user_id', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('original_address', models.CharField(max_length=30)),
            ],
        ),
    ]
