# Generated by Django 3.1.3 on 2021-08-10 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_menu', '0006_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='req_url',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
