# Generated by Django 3.1.3 on 2021-08-11 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_menu', '0013_rest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rest',
        ),
    ]
