# Generated by Django 3.1.3 on 2021-08-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_menu', '0015_rest'),
    ]

    operations = [
        migrations.AddField(
            model_name='rest',
            name='img',
            field=models.ImageField(null=True, upload_to='rests_pic'),
        ),
    ]
