# Generated by Django 3.1.3 on 2021-08-30 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_menu', '0016_rest_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
